# Generated by Django 4.1.2 on 2022-10-29 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0003_alter_category_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True, verbose_name='Nombre del producto')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Enlace')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Descripción')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('images', models.ImageField(upload_to='photos/products', verbose_name='Imagen')),
                ('stock', models.IntegerField(verbose_name='Existencias')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Categoria')),
            ],
        ),
    ]
