# Generated by Django 4.1.2 on 2022-10-31 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_category', models.CharField(choices=[('color', 'color'), ('seze', 'size')], max_length=100, verbose_name='Categoría de variación')),
                ('variation_value', models.CharField(max_length=100, verbose_name='Valor de variación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Es activo')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Prodcuto')),
            ],
            options={
                'verbose_name': 'variacion',
                'verbose_name_plural': 'variaciones',
            },
        ),
    ]
