# Generated by Django 4.1.2 on 2022-10-31 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'carrito', 'verbose_name_plural': 'carritos'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'artículo del carro', 'verbose_name_plural': 'artículos del carrito'},
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='is_activo',
            new_name='is_active',
        ),
    ]
