# Generated by Django 4.1.2 on 2022-10-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True, verbose_name='Nombre categoría')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Enlace')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Descripción')),
                ('cat_image', models.ImageField(blank=True, upload_to='photos/categories', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha edición')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
    ]
